Initial Classes
Dhii/invoker-base pull request #1
Opened 2017-12-27 21:30 UTC by XedinUnknown

This contains the exception classes.

2017-12-28 08:50 UTC, mecha requested changes

2017-12-28 08:50 UTC, mecha commented on composer.json
> +        "dhii/stringable-interfeace": "^0.1"
Ijja?

2017-12-28 08:51 UTC, XedinUnknown commented on composer.json
> +        "dhii/stringable-interfeace": "^0.1"
😮 Interfeces....

2017-12-28 08:52 UTC, mecha commented on composer.json
> +        "dhii/stringable-interfeace": "^0.1"
Ostja

2017-12-28 08:57 UTC, XedinUnknown commented on composer.json
> +        "dhii/stringable-interfeace": "^0.1"
Mela

2017-12-28 15:27 UTC, mecha requested changes

2017-12-28 15:27 UTC, mecha commented on src/Exception/AbstractBaseCommandInvokerException.php
> +    use NormalizeStringCapableTrait;
Unused in this class.

2017-12-28 15:27 UTC, mecha commented on src/Exception/AbstractBaseCommandInvokerException.php
> +    use NormalizeIntCapableTrait;
Unused in this class.

2017-12-28 15:27 UTC, mecha commented on src/Exception/CommandInvokerException.php
> +    /**
Consider using `NormalizeStringCapableTrait` and `NormalizeIntCapableTrait` here instead of in `AbstractBaseCommandInvokerException`.

2017-12-28 15:27 UTC, mecha commented on src/Exception/InvocationFailureException.php
> +    /*
Consider using `NormalizeStringCapableTrait` and `NormalizeIntCapableTrait` here instead of in `AbstractBaseCommandInvokerException`.

2017-12-29 16:44 UTC, XedinUnknown commented
Was going to write that having the abstract class use normalization traits saves time, but then had another look and agree that having the concretes use normalization traits makes the source of implementation more obvious.

2017-12-29 16:55 UTC, merged